#示例
listenAddr: ":8080"
timeout: 10s
jwtConfig:
  secret_key: "your-access-secret"
  issuer: "gateway"
  refresh_secret: "your-refresh-secret"
zapConfig:
  level: "info"
  encoding: "json"
  output_path: "stdout"
  error_output: "stderr"
rateLimitConfig:
  capacity: 100
  refill_interval: 1s
  cleanup_interval: 5m
  idle_timeout: 10m
services:
  - name: "user-service"
    host: "user-service"
    port: 8080
    prefix: "/api/user"
    routes:
      - path: /users
        allowedRoles:
           - Admin
           - User
      - path: /admin
        allowedRoles:
        - Admin
  - name: "post-service"
    host: "post-service"
    port: 8081
    prefix: "/api/post"
    allowedRoles:
      - "admin"

server:
  listen_addr: ":8080"
  # ...
cors:
  allow_origins:
    - "http://localhost:8000" # 开发环境前端地址
    - "http://127.0.0.1:8000"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
  max_age: 43200 # 12 hours
# ... 其他配置 ...
logger:
  level: "debug"
  encoding: "console"
tracing:
  enabled: true
  # ...